// Achievement Keys Storage
// Add your achievement keys here
const achievementKeys = [
	// Example format:
	// "eyJnYW1lSWQiOiJodG1sLWJhc2ljcy0xIiwidGltZXN0YW1wIjoxNjg1NDcyMDAwLCJhY2hpZXZlbWVudHMiOlt7InNraWxsSWQiOiJodG1sIiwicG9pbnRzIjoxNSwibGV2ZWwiOjEsImRlc2NyaXB0aW9uIjoiQ29tcGxldGVkIEhUTUwgYmFzaWNzIGNoYWxsZW5nZSJ9XSwic2lnbmF0dXJlIjoiZGVtby1zaWduYXR1cmUtMTIzNDUifQ==",

	// Add your real achievement keys below:
"eyJnYW1lSWQiOiJpbnRlcm5ldC1iYXNpY3MiLCJ0aW1lc3RhbXAiOjE3NDU3NDA1MTAsImFjaGlldmVtZW50cyI6W3sic2tpbGxJZCI6ImludGVybmV0IiwicG9pbnRzIjoyMCwibGV2ZWwiOjEsImRlc2NyaXB0aW9uIjoiTWFzdGVyZWQgaW50ZXJuZXQgYmFzaWNzIGNvbmNlcHRzIn0seyJza2lsbElkIjoibmV0d29ya2luZyIsInBvaW50cyI6MTUsImxldmVsIjoxLCJkZXNjcmlwdGlvbiI6IkxlYXJuZWQgSFRUUCBwcm90b2NvbCBiYXNpY3MifSx7InNraWxsSWQiOiJwcm9ibGVtLXNvbHZpbmciLCJwb2ludHMiOjEwLCJsZXZlbCI6MSwiZGVzY3JpcHRpb24iOiJDb21wbGV0ZWQgbmV0d29yayB0cm91Ymxlc2hvb3RpbmcgY2hhbGxlbmdlIn1dLCJzaWduYXR1cmUiOiJmYWxsYmFja19hbmczMDlrcnVjaSJ9",
];

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
	module.exports = achievementKeys;
}
